### PR TITLE
Test Github commit ordering

### PR DESCRIPTION
**Pull request by agirault**
Checking if [this](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-in-the-wrong-order) still applies:

> Screen Shot 2019-10-29 at 3 39 59 PM

Based on discussions here: https://github.com/isaacs/github/issues/386

### CODE REVIEW

**Comment by agirault** [comment]
Pushed the commits where 2nd commit chronologically is the 2nd commit topologically, and 3rd commit chronologically is the 3rd commit topologically. About to switch those two commits topologically with rebase then force push

**Comment by agirault** [comment]
After switching the two commits order, they go from this:

> Screen Shot 2019-10-29 at 2 58 06 PM
> Screen Shot 2019-10-29 at 2 58 12 PM

to this:

> Screen Shot 2019-10-29 at 2 58 36 PM
> Screen Shot 2019-10-29 at 2 58 46 PM

It does seem the commits were re-ordered on GitHub to follow the topological order as well.

**Comment by agirault** [comment]
After merging, we can confirm the topological order is shown in GitHub.

> Screen Shot 2019-10-29 at 3 02 46 PM

**Comment by larsbrinkhoff** [comment]
I don't see that this is fixed in the pull request view.  EDIT: In one of my own pull requests.  Not a comment on this pull request.

**Comment by agirault** [comment]
@larsbrinkhoff can you share that? Is that an old PR? Looks good in that one here.

**Comment by larsbrinkhoff** [comment]
Sure!  This is my test done just minutes ago:

https://github.com/larsbrinkhoff/test-commit-order/pull/1

**Pull request merged**
